# Generated by Django 5.2.15 on 2026-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_avaliacao", "Em Avaliação"),
                    ("corrigida", "Corrigida"),
                    ("erro", "Erro na correção"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
