# Generated by Django 5.2.15 on 2026-07-09 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0005_corretorllm_descricao_poolcorrecao_descricao_and_more"),
        ("redacoes", "0002_redacao_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenciaRota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("padrao", "Usar banca padrão do sistema"),
                            ("banca", "Banca específica"),
                            ("corretores", "Corretores específicos"),
                        ],
                        default="padrao",
                        max_length=20,
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferencias_rota",
                        to="corretores.poolcorrecao",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencia_rota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferência de rota",
                "verbose_name_plural": "Preferências de rota",
                "db_table": "preferencias_rota",
            },
        ),
        migrations.CreateModel(
            name="PreferenciaRotaCorretor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "pool_corretor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_rota",
                        to="corretores.poolcorretor",
                    ),
                ),
                (
                    "preferencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corretores_selecionados",
                        to="redacoes.preferenciarota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corretor selecionado na rota",
                "verbose_name_plural": "Corretores selecionados na rota",
                "db_table": "preferencias_rota_corretores",
                "unique_together": {("preferencia", "pool_corretor")},
            },
        ),
    ]
