# Generated by Django 5.2.15 on 2026-07-10 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redacoes", "0003_preferenciarota_preferenciarotacorretor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemaRedacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título do tema"),
                ),
                ("texto", models.TextField(verbose_name="Texto do tema")),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="temas/",
                        verbose_name="Imagem (opcional)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temas_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema de redação",
                "verbose_name_plural": "Temas de redação",
                "db_table": "temas_redacao",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="redacao",
            name="tema_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redacoes",
                to="redacoes.temaredacao",
            ),
        ),
    ]
