# Generated by Django 5.2.15 on 2026-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redacoes", "0004_temaredacao_redacao_tema_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redacao",
            name="tema",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
