# Generated by Django 5.2.15 on 2026-07-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redacoes", "0005_alter_redacao_tema"),
    ]

    operations = [
        migrations.AddField(
            model_name="redacao",
            name="excluida_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
