# Generated by Django 5.2.15 on 2026-07-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0020_incluir_toggles_protocolo"),
        ("redacoes", "0006_redacao_excluida_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="redacao",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redacoes",
                to="corretores.poolcorrecao",
            ),
        ),
    ]
