# Generated by Django 5.2.15 on 2026-07-17 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professores_turma'),
        ('corretores', '0025_copiloto_models'),
        ('redacoes', '0007_add_pool_to_redacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAvaliativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da atividade')),
                ('prazo', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de entrega')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('copiloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='corretores.correcaocopiloto', verbose_name='Copiloto de correção')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='redacoes.temaredacao')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='accounts.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Atividade avaliativa',
                'verbose_name_plural': 'Atividades avaliativas',
                'db_table': 'atividades_avaliativas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='redacao',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redacoes', to='redacoes.atividadeavaliativa', verbose_name='Atividade avaliativa'),
        ),
    ]
