# Generated by Django 5.2.15 on 2026-07-17 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professores_turma'),
        ('corretores', '0025_copiloto_models'),
        ('redacoes', '0008_copiloto_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeavaliativa',
            name='turmas',
            field=models.ManyToManyField(related_name='atividades', to='accounts.turma', verbose_name='Turmas'),
        ),
        migrations.RunSQL(
            sql="INSERT INTO atividades_avaliativas_turmas (atividadeavaliativa_id, turma_id) SELECT id, turma_id FROM atividades_avaliativas WHERE turma_id IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='atividadeavaliativa',
            name='turma',
        ),
        migrations.AlterField(
            model_name='atividadeavaliativa',
            name='copiloto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='corretores.correcaocopiloto', verbose_name='Copiloto de correção'),
        ),
    ]
