# Generated by Django 5.2.15 on 2026-07-17 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_escola_customuser_escola_turma_customuser_turma_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Pluma user', 'verbose_name_plural': 'Pluma users'},
        ),
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='turmas_ministradas', to=settings.AUTH_USER_MODEL, verbose_name='Professores da turma'),
        ),
    ]
