# Generated by Django 5.2.15 on 2026-07-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_email_verification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="codigo_convite",
            field=models.CharField(
                blank=True, default=None, max_length=12, null=True, unique=True
            ),
        ),
    ]
