# Generated by Django 5.2.15 on 2026-07-07 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorretorLLM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("provedor", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "corretores_llm",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PoolCorrecao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "metodo",
                    models.CharField(
                        choices=[("mediana", "Mediana"), ("media", "Média")],
                        default="mediana",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pools_correcao",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PoolCorretor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("llm", "LLM"), ("humano", "Humano")], max_length=20
                    ),
                ),
                ("peso", models.FloatField(default=1.0)),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "corretor_llm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_pool",
                        to="corretores.corretorllm",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corretores",
                        to="corretores.poolcorrecao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_pool",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pool_corretores",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
