# Generated by Django 5.2.15 on 2026-07-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0003_provedorllm_corretorllm_provedor_str_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corretorllm",
            options={
                "ordering": ["nome"],
                "verbose_name": "Corretor IA",
                "verbose_name_plural": "Corretores IA",
            },
        ),
        migrations.AlterModelOptions(
            name="poolcorrecao",
            options={
                "ordering": ["nome"],
                "verbose_name": "Banca de correção",
                "verbose_name_plural": "Bancas de correção",
            },
        ),
        migrations.AlterModelOptions(
            name="poolcorretor",
            options={
                "ordering": ["ordem", "id"],
                "verbose_name": "Membro da banca",
                "verbose_name_plural": "Membros da banca",
            },
        ),
        migrations.AlterModelOptions(
            name="provedorllm",
            options={
                "ordering": ["nome"],
                "verbose_name": "Provedor IA",
                "verbose_name_plural": "Provedores IA",
            },
        ),
    ]
