# Generated by Django 5.2.15 on 2026-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "corretores",
            "0004_alter_corretorllm_options_alter_poolcorrecao_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="corretorllm",
            name="descricao",
            field=models.TextField(
                blank=True, help_text="Habilidades e foco deste corretor IA"
            ),
        ),
        migrations.AddField(
            model_name="poolcorrecao",
            name="descricao",
            field=models.TextField(
                blank=True, help_text="Descrição da banca de correção"
            ),
        ),
        migrations.AddField(
            model_name="poolcorretor",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Habilidades e especialidades deste corretor (humano)",
            ),
        ),
    ]
