# Generated by Django 5.2.15 on 2026-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0005_corretorllm_descricao_poolcorrecao_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corretorllm",
            name="competencias",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de competências em que o agente é especialista",
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="ferramentas",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de ferramentas habilitadas para este agente",
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="prompt_personalizado",
            field=models.TextField(
                blank=True,
                help_text="Prompt customizado que substitui o template base quando preenchido",
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="prompt_template",
            field=models.CharField(
                choices=[
                    ("detalhado", "Avaliador Detalhado"),
                    ("conciso", "Avaliador Conciso"),
                    ("minimo", "Avaliador Mínimo"),
                ],
                default="detalhado",
                help_text="Template base do prompt de avaliação",
                max_length=50,
            ),
        ),
    ]
