# Generated by Django 5.2.15 on 2026-07-09 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "corretores",
            "0006_corretorllm_competencias_corretorllm_ferramentas_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Ferramenta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("ativa_por_padrao", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ferramenta",
                "verbose_name_plural": "Ferramentas",
                "db_table": "ferramentas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Nome do template", max_length=255),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("base", "Base"), ("custom", "Customizado")],
                        default="base",
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "sistema_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Instrução de sistema (sem o formato de saída)",
                    ),
                ),
                (
                    "formato_saida",
                    models.TextField(
                        blank=True,
                        help_text="Bloco com o formato JSON que o LLM deve retornar (incluído no final do sistema_prompt)",
                    ),
                ),
                (
                    "competencias_padrao",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de competências que este template cobre",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template de prompt",
                "verbose_name_plural": "Templates de prompt",
                "db_table": "prompts_template",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "competencias",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Competências relacionadas a esta skill",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone (emoji ou classe CSS)",
                        max_length=50,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "skills",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="ferramentas_ativas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ferramentas ativas para este agente",
                related_name="corretores",
                to="corretores.ferramenta",
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="prompt_template_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Referência ao template de prompt salvo no banco",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corretores",
                to="corretores.prompttemplate",
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills vinculadas a este agente",
                related_name="corretores",
                to="corretores.skill",
            ),
        ),
    ]
