# Generated by Django 5.2.15 on 2026-07-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0010_seed_skills_enem"),
    ]

    operations = [
        migrations.AddField(
            model_name="corretorllm",
            name="subagentes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subagentes especialistas que este orquestrador coordena",
                related_name="orquestradores",
                to="corretores.corretorllm",
            ),
        ),
    ]
