# Generated by Django 5.2.15 on 2026-07-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0011_corretorllm_subagentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="poolcorrecao",
            name="limiar_desvio",
            field=models.FloatField(
                default=20.0,
                help_text="Desvio padrão máximo por competência antes de acionar o revisor LLM",
            ),
        ),
    ]
