# Generated by Django 5.2.15 on 2026-07-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0013_poolcorrecao_revisor_corretor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poolcorrecao",
            name="revisor_corretor",
            field=models.ForeignKey(
                blank=True,
                help_text="Corretor cujo provedor/modelo será usado para o revisor de consenso",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bancas_como_revisor",
                to="corretores.corretorllm",
            ),
        ),
    ]
