# Generated by Django 5.2.15 on 2026-07-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0014_alter_poolcorrecao_revisor_corretor"),
    ]

    operations = [
        migrations.AddField(
            model_name="corretorllm",
            name="output_json",
            field=models.BooleanField(
                default=True,
                help_text="Ativar response_format json_object (OpenAI) ou equivalente",
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="seed",
            field=models.IntegerField(
                blank=True,
                help_text="Seed fixa para reprodutibilidade (ex: 42)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Temperatura para geração (0 = determinístico, 1 = criativo)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="top_p",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                help_text="Nucleus sampling (top_p): 0 = mínimo, 1 = máximo",
                max_digits=3,
            ),
        ),
    ]
