# Generated by Django 5.2.15 on 2026-07-12 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0015_corretorllm_output_json_corretorllm_seed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubrica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "competencia",
                    models.CharField(
                        choices=[
                            ("c1", "Competência 1 — Norma padrão"),
                            ("c2", "Competência 2 — Tema e estrutura"),
                            ("c3", "Competência 3 — Argumentação"),
                            ("c4", "Competência 4 — Coesão e coerência"),
                            ("c5", "Competência 5 — Proposta de intervenção"),
                        ],
                        max_length=2,
                    ),
                ),
                ("versao", models.IntegerField(default=1)),
                (
                    "ativa",
                    models.BooleanField(
                        default=False,
                        help_text="Apenas uma rubrica ativa por competência",
                    ),
                ),
                (
                    "arvore",
                    models.JSONField(
                        default=dict,
                        help_text="Árvore de decisão em JSON: passos com perguntas e regras",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, help_text="Instruções adicionais para o avaliador"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rubrica",
                "verbose_name_plural": "Rubricas",
                "db_table": "rubricas",
                "ordering": ["competencia", "-versao"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competencia", "versao"),
                        name="rubrica_competencia_versao_unica",
                    )
                ],
            },
        ),
    ]
