# Generated by Django 5.2.15 on 2026-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0016_rubrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolcorrecao',
            name='modo',
            field=models.CharField(choices=[('pool', 'Pool de agentes'), ('especialistas', 'Especialistas C1-C5')], default='pool', help_text='Modo de avaliação: pool usa os membros da banca, especialistas usa 5 agentes C1-C5', max_length=20),
        ),
    ]
