# Generated by Django 5.2.15 on 2026-07-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0017_pool_modo_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolcorrecao',
            name='modelo_llm',
            field=models.CharField(blank=True, help_text='Modelo para o modo especialistas (ex: gpt-4o). Vazio = usa LLM_MODEL do .env', max_length=255),
        ),
        migrations.AddField(
            model_name='poolcorrecao',
            name='provedor',
            field=models.ForeignKey(blank=True, help_text='Provedor padrão usado no modo especialistas (API key + base URL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='corretores.provedorllm'),
        ),
        migrations.AddField(
            model_name='provedorllm',
            name='tipo',
            field=models.CharField(choices=[('openai', 'OpenAI / Compatível'), ('gemini', 'Google Gemini')], default='openai', help_text='Tipo de provedor: OpenAI/compatível ou Gemini', max_length=20),
        ),
        migrations.AlterField(
            model_name='poolcorrecao',
            name='modo',
            field=models.CharField(choices=[('pool', 'Pool de agentes'), ('especialistas', 'Especialistas C1-C5')], default='pool', help_text='Modo de avaliação: pool usa membros da banca, especialistas usa 5 agentes C1-C5', max_length=20),
        ),
    ]
