# Generated by Django 5.2.15 on 2026-07-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corretores", "0019_remove_provedorllm_modelos"),
    ]

    operations = [
        migrations.AddField(
            model_name="corretorllm",
            name="incluir_base_conhecimento",
            field=models.BooleanField(
                default=False,
                help_text="Incluir redações nota 1000 como referência no prompt do sistema",
            ),
        ),
        migrations.AddField(
            model_name="corretorllm",
            name="incluir_protocolo_enem",
            field=models.BooleanField(
                default=True,
                help_text="Incluir o protocolo oficial de avaliação ENEM no prompt do sistema",
            ),
        ),
    ]
