# Generated by Django 5.2.15 on 2026-07-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0020_incluir_toggles_protocolo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolcorrecao',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Banca de correção', 'verbose_name_plural': 'Bancas de correção'},
        ),
        migrations.AddField(
            model_name='poolcorrecao',
            name='limite_concorrencia',
            field=models.PositiveIntegerField(default=10, help_text='Máximo de redações simultâneas antes de extravasar para a próxima banca'),
        ),
        migrations.AddField(
            model_name='poolcorrecao',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de prioridade na distribuição (menor = maior prioridade)'),
        ),
    ]
