# Generated by Django 5.2.15 on 2026-07-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0022_preencher_ordem_bancas'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretorllm',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Score 0-10 calculado com base nos feedbacks do admin'),
        ),
        migrations.AddField(
            model_name='corretorllm',
            name='rating_atualizado_em',
            field=models.DateTimeField(blank=True, help_text='Última vez que o rating foi recalculado', null=True),
        ),
    ]
