# Generated by Django 5.2.15 on 2026-07-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0023_corretorllm_rating_corretorllm_rating_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolcorrecao',
            name='parametros_revisor',
            field=models.JSONField(blank=True, default=dict, help_text='Parâmetros da regra. Ex: {"limiar_total": 100, "limiar_competencia": 80}'),
        ),
        migrations.AddField(
            model_name='poolcorrecao',
            name='regra_revisor',
            field=models.CharField(choices=[('desvio_padrao', 'Desvio Padrão (comportamento atual)'), ('diferenca_enem', 'Diferença ENEM (total > 100 OU competência > 80)'), ('personalizada', 'Regra personalizada (via JSON)')], default='desvio_padrao', help_text='Regra que determina quando o revisor é chamado', max_length=30),
        ),
        migrations.AlterField(
            model_name='poolcorrecao',
            name='limiar_desvio',
            field=models.FloatField(default=20.0, help_text="Desvio padrão máximo por competência antes de acionar o revisor LLM (usado apenas se regra_revisor='desvio_padrao')"),
        ),
    ]
