# Generated by Django 5.2.15 on 2026-07-17 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0024_poolcorrecao_parametros_revisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoCopiloto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do copiloto')),
                ('merge_strategy', models.CharField(choices=[('professor_override', 'Professor sobrescreve')], default='professor_override', max_length=30)),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('corretor_llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilotos', to='corretores.corretorllm', verbose_name='Corretor IA')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilotos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Copiloto de correção',
                'verbose_name_plural': 'Copilotos de correção',
                'db_table': 'correcoes_copiloto',
                'ordering': ['-criado_em'],
            },
        ),
    ]
