from __future__ import annotations

from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("dashboard/api/nav-counts", views.api_nav_counts, name="dashboard-api-nav-counts"),
    path("dashboard/api/ultima-corrigida", views.api_ultima_corrigida, name="dashboard-api-ultima-corrigida"),
    path("login", views.login_view, name="login"),
    path("register", views.register_view, name="register"),
    path("entrar-turma/<str:codigo>", views.entrar_turma, name="entrar-turma"),
    path("verify-email/<uuid:token>", views.verify_email, name="dashboard-verify-email"),
    path("logout", views.logout_view, name="logout"),
    path("dashboard/submeter", views.submeter, name="dashboard-submeter"),
    path("dashboard/minhas-redacoes", views.minhas_redacoes, name="dashboard-minhas-redacoes"),
    path("dashboard/redacao/<uuid:redacao_id>", views.detalhe_redacao, name="dashboard-detalhe-redacao"),
    path("dashboard/resubmeter/<uuid:redacao_id>", views.resubmeter, name="dashboard-resubmeter"),
    path("dashboard/corrigir", views.corrigir, name="dashboard-corrigir"),
    path("dashboard/minhas-correcoes", views.minhas_correcoes, name="dashboard-minhas-correcoes"),
    path("dashboard/editar-correcao/<uuid:avaliacao_id>", views.editar_correcao, name="dashboard-editar-correcao"),
    path("dashboard/turma", views.turma, name="dashboard-turma"),
    path("dashboard/turma/nova", views.turma_form, name="dashboard-turma-nova"),
    path("dashboard/turma/<uuid:turma_id>/editar", views.turma_form, name="dashboard-turma-editar"),
    path("dashboard/turma/<uuid:turma_id>/excluir", views.turma_excluir, name="dashboard-turma-excluir"),
    path(
        "dashboard/turma/<uuid:turma_id>/alunos/adicionar",
        views.turma_adicionar_aluno,
        name="dashboard-turma-adicionar-aluno",
    ),
    path(
        "dashboard/turma/<uuid:turma_id>/alunos/<uuid:aluno_id>/remover",
        views.turma_remover_aluno,
        name="dashboard-turma-remover-aluno",
    ),
    path(
        "dashboard/turma/<uuid:turma_id>/alunos/remover",
        views.turma_remover_alunos,
        name="dashboard-turma-remover-alunos",
    ),
    path("dashboard/estatisticas", views.estatisticas, name="dashboard-estatisticas"),
    path("dashboard/fila", views.fila, name="dashboard-fila"),
    path("dashboard/fila/redisparar/<uuid:redacao_id>", views.fila_redisparar, name="fila-redisparar"),
    path("dashboard/fila/retentar/<uuid:redacao_id>/<uuid:pool_corretor_id>", views.fila_retentar_corretor, name="fila-retentar-corretor"),
    path("dashboard/fila/forcar-consolidacao/<uuid:redacao_id>", views.fila_forcar_consolidacao, name="fila-forcar-consolidacao"),
    path("dashboard/fila/remover-queue/<int:queue_id>", views.fila_remover_queue, name="fila-remover-queue"),
    path("dashboard/relatorios", views.relatorios, name="dashboard-relatorios"),
    path("dashboard/relatorios/corretores", views.relatorios_corretores, name="dashboard-relatorios-corretores"),
    path("dashboard/bancas", views.bancas, name="bancas"),
    path("dashboard/bancas/<uuid:banca_id>", views.banca_detalhe, name="banca-detalhe"),
    path("dashboard/bancas/<uuid:banca_id>/membros/<uuid:membro_id>", views.membro_detalhe, name="membro-detalhe"),
    path("dashboard/agentes", views.agentes, name="agentes"),
    path("dashboard/agentes/<uuid:agente_id>", views.agente_detalhe, name="agente-detalhe"),
    path("dashboard/agentes/prompts", views.agentes_prompts, name="agentes-prompts"),
    path("dashboard/agentes/prompts/novo", views.agente_prompt_form, name="agente-prompt-novo"),
    path("dashboard/agentes/prompts/<uuid:prompt_id>", views.agente_prompt_form, name="agente-prompt-editar"),
    path("dashboard/agentes/skills", views.admin_skills, name="admin-skills"),
    path("dashboard/agentes/skills/novo", views.admin_skill_form, name="admin-skill-novo"),
    path("dashboard/agentes/skills/<uuid:skill_id>", views.admin_skill_form, name="admin-skill-editar"),
    path("dashboard/agentes/ferramentas", views.admin_ferramentas, name="admin-ferramentas"),
    path("dashboard/agentes/ferramentas/novo", views.admin_ferramenta_form, name="admin-ferramenta-novo"),
    path("dashboard/agentes/ferramentas/<uuid:ferramenta_id>", views.admin_ferramenta_form, name="admin-ferramenta-editar"),
    path("dashboard/configuracoes", views.configuracoes, name="dashboard-configuracoes"),
    path("dashboard/configuracoes/provedores", views.admin_provedores, name="admin-provedores"),
    path("dashboard/configuracoes/provedores/adicionar", views.admin_provedor_form, name="admin-provedor-add"),
    path("dashboard/configuracoes/provedores/<uuid:provedor_id>/editar", views.admin_provedor_form, name="admin-provedor-edit"),
    path("dashboard/configuracoes/corretores", views.admin_corretores, name="admin-corretores"),
    path("dashboard/configuracoes/corretores/adicionar", views.admin_corretor_form, name="admin-corretor-add"),
    path("dashboard/configuracoes/corretores/<uuid:corretor_id>/editar", views.admin_corretor_form, name="admin-corretor-edit"),
    path("dashboard/rota-correcao", views.rota_correcao, name="rota-correcao"),
    path("dashboard/notificacoes", views.notificacoes, name="notificacoes"),
    path("dashboard/notificacoes/limpar", views.limpar_notificacoes, name="limpar-notificacoes"),
    path("dashboard/configuracoes/temas", views.admin_temas, name="admin-temas"),
    path("dashboard/configuracoes/temas/novo", views.admin_tema_form, name="admin-tema-novo"),
    path("dashboard/configuracoes/temas/<uuid:tema_id>/editar", views.admin_tema_form, name="admin-tema-editar"),
    path("dashboard/debug", views.debug_lista, name="debug-lista"),
    path("dashboard/debug/<uuid:redacao_id>", views.debug_detalhe, name="debug-detalhe"),
    path("dashboard/debug/<uuid:redacao_id>/feedback/<uuid:avaliacao_id>", views.debug_feedback, name="debug-feedback"),
    path("dashboard/configuracoes/rubricas", views.rubricas, name="rubricas"),
    path("dashboard/configuracoes/rubricas/novo", views.rubrica_form, name="rubrica-novo"),
    path(
        "dashboard/configuracoes/rubricas/<uuid:rubrica_id>",
        views.rubrica_form,
        name="rubrica-editar",
    ),
    path("dashboard/copiloto", views.copiloto_lista, name="copiloto-lista"),
    path("dashboard/copiloto/novo", views.copiloto_form, name="copiloto-novo"),
    path("dashboard/copiloto/<uuid:copiloto_id>/editar", views.copiloto_form, name="copiloto-editar"),
    path("dashboard/copiloto/pendentes", views.copiloto_pendentes, name="copiloto-pendentes"),
    path("dashboard/copiloto/revisar/<uuid:avaliacao_id>", views.copiloto_revisar, name="copiloto-revisar"),
    path("dashboard/copiloto/liberar/<uuid:avaliacao_id>", views.copiloto_liberar, name="copiloto-liberar"),
    path("dashboard/atividades", views.atividades_lista, name="atividades-lista"),
    path("dashboard/atividades/nova", views.atividade_form, name="atividade-nova"),
    path("dashboard/atividades/<uuid:atividade_id>/editar", views.atividade_form, name="atividade-editar"),
    path("dashboard/atividades/<uuid:atividade_id>/excluir", views.atividade_excluir, name="atividade-excluir"),
    path("dashboard/minhas-atividades", views.minhas_atividades, name="minhas-atividades"),
    path("dashboard/atividades/<uuid:atividade_id>/aluno", views.atividade_aluno, name="atividade-aluno"),
    path("dashboard/copiloto/<uuid:copiloto_id>/excluir", views.copiloto_excluir, name="copiloto-excluir"),
]
