# Generated by Django 5.2.15 on 2026-07-07 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corretores", "0001_initial"),
        ("redacoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("c1_nota", models.IntegerField(default=0)),
                ("c1_justificativa", models.TextField(default="")),
                ("c1_sugestoes", models.TextField(default="")),
                ("c2_nota", models.IntegerField(default=0)),
                ("c2_justificativa", models.TextField(default="")),
                ("c2_sugestoes", models.TextField(default="")),
                ("c3_nota", models.IntegerField(default=0)),
                ("c3_justificativa", models.TextField(default="")),
                ("c3_sugestoes", models.TextField(default="")),
                ("c4_nota", models.IntegerField(default=0)),
                ("c4_justificativa", models.TextField(default="")),
                ("c4_sugestoes", models.TextField(default="")),
                ("c5_nota", models.IntegerField(default=0)),
                ("c5_justificativa", models.TextField(default="")),
                ("c5_sugestoes", models.TextField(default="")),
                ("nota_total", models.IntegerField(default=0)),
                ("avaliador", models.CharField(default="", max_length=255)),
                ("modelo_llm", models.CharField(default="", max_length=255)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "avaliador_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaliacoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaliacoes",
                        to="corretores.poolcorrecao",
                    ),
                ),
                (
                    "redacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="redacoes.redacao",
                    ),
                ),
            ],
            options={
                "db_table": "avaliacoes",
                "ordering": ["-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="Consolidacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nota_total", models.IntegerField(default=0)),
                ("c1_nota", models.IntegerField(default=0)),
                ("c1_justificativa", models.TextField(default="")),
                ("c2_nota", models.IntegerField(default=0)),
                ("c2_justificativa", models.TextField(default="")),
                ("c3_nota", models.IntegerField(default=0)),
                ("c3_justificativa", models.TextField(default="")),
                ("c4_nota", models.IntegerField(default=0)),
                ("c4_justificativa", models.TextField(default="")),
                ("c5_nota", models.IntegerField(default=0)),
                ("c5_justificativa", models.TextField(default="")),
                ("status", models.CharField(default="parcial", max_length=20)),
                ("quantidade_corretores", models.IntegerField(default=0)),
                ("quantidade_esperada", models.IntegerField(default=0)),
                ("metodo", models.CharField(default="mediana", max_length=20)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidacoes",
                        to="corretores.poolcorrecao",
                    ),
                ),
                (
                    "redacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidacoes",
                        to="redacoes.redacao",
                    ),
                ),
            ],
            options={
                "db_table": "consolidacoes",
                "unique_together": {("redacao", "pool")},
            },
        ),
    ]
