# Generated by Django 5.2.15 on 2026-07-07 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anotacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trecho_inicio", models.IntegerField()),
                ("trecho_fim", models.IntegerField()),
                ("trecho_texto", models.CharField(max_length=500)),
                (
                    "tipo_erro",
                    models.CharField(
                        choices=[
                            ("ortografia", "Ortografia / Grafia incorreta"),
                            ("concordancia", "Concordância verbal / nominal"),
                            ("pontuacao", "Pontuação"),
                            ("coesao", "Coesão / Conectivos"),
                            ("vocabulario", "Vocabulário / Registro"),
                            ("argumentacao", "Argumentação / Lógica"),
                            ("clareza", "Clareza / Estrutura da frase"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comentario", models.TextField(blank=True, default="")),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anotacoes",
                        to="avaliacoes.avaliacao",
                    ),
                ),
            ],
            options={
                "db_table": "anotacoes",
                "ordering": ["trecho_inicio"],
            },
        ),
    ]
