# Generated by Django 5.2.15 on 2026-07-08 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0004_alter_avaliacao_rascunho"),
        ("redacoes", "0002_redacao_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="avaliacao",
            unique_together={("redacao", "avaliador_usuario")},
        ),
    ]
