# Generated by Django 5.2.15 on 2026-07-09 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0005_alter_avaliacao_unique_together"),
        ("redacoes", "0003_preferenciarota_preferenciarotacorretor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("correcao_solicitada", "Correção solicitada"),
                            ("correcao_aceita", "Correção aceita"),
                            ("correcao_recusada", "Correção recusada"),
                            ("correcao_concluida", "Correção concluída"),
                        ],
                        max_length=30,
                    ),
                ),
                ("mensagem", models.TextField()),
                ("lida", models.BooleanField(default=False)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "redacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="redacoes.redacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "db_table": "notificacoes",
                "ordering": ["-criada_em"],
            },
        ),
    ]
