# Generated by Django 5.2.15 on 2026-07-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0006_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="consolidacao",
            name="parecer_revisor",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="consolidacao",
            name="revisado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consolidacao",
            name="usou_revisor_llm",
            field=models.BooleanField(default=False),
        ),
    ]
