# Generated by Django 5.2.15 on 2026-07-11 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacoes", "0007_consolidacao_parecer_revisor_and_more"),
        ("corretores", "0014_alter_poolcorrecao_revisor_corretor"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="corretor_llm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avaliacoes",
                to="corretores.corretorllm",
            ),
        ),
    ]
