# Generated by Django 5.2.15 on 2026-07-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0008_avaliacao_corretor_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='debug_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
