# Generated by Django 5.2.15 on 2026-07-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0009_avaliacao_debug_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='admin_feedback',
            field=models.CharField(blank=True, default='', help_text="Feedback do admin: 'bom' | 'ruim' | '' (sem feedback)", max_length=10),
        ),
    ]
