# Generated by Django 5.2.15 on 2026-07-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0010_avaliacao_admin_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='feedback_professor',
            field=models.JSONField(blank=True, default=dict, help_text='Feedback do professor na revisão: notas editadas, justificativas, comentários'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='liberada_em',
            field=models.DateTimeField(blank=True, help_text='Data em que o professor liberou a correção para o aluno', null=True),
        ),
    ]
