# Generated by Django 5.2.15 on 2026-07-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0011_copiloto_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('correcao_solicitada', 'Correção solicitada'), ('correcao_aceita', 'Correção aceita'), ('correcao_recusada', 'Correção recusada'), ('correcao_concluida', 'Correção concluída'), ('nova_atividade', 'Nova atividade disponível')], max_length=30),
        ),
    ]
